# -*- coding: utf-8 -*-
"""st dss gdg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKWl8qr_2NzVrRZfADLuzNvkq_2rztT0
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df = pd.read_csv('DataScience_salaries_2024.csv')

# Convert categorical variables to numerical
le = LabelEncoder()
for column in df.columns:
    if df[column].dtype == type(object):
        df[column] = le.fit_transform(df[column])

# Set the title of the app
st.title('Data Analysis Dashboard')

# Display the dataset
st.header('Dataset')
st.write(df)

# Display descriptive statistics
st.header('Descriptive Statistics')
st.write(df.describe())

# Display the correlation matrix
st.header('Correlation Matrix')
corr = df.corr()
fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(corr, annot=True, ax=ax, cmap='coolwarm')
st.pyplot(fig)